from __future__ import annotations

import configparser
import json
import os
import shutil
import subprocess
import sys
import tempfile
from typing import Any
from pathlib import Path


WALL_DIR = Path.home() / "Pictures"
ROFI_CMD = ["rofi", "-dmenu", "-i", "-p", "Wallpaper"]
SWWW_CMD = ["swww", "img"]
WAL_CMD = ["wal", "-i"]
KITTY_CMD = [
    "kitty",
    "@",
    "set-colors",
    "--all",
    "--configured",
    str(Path.home() / ".cache/wal/colors-kitty.conf"),
]
NVIM_REMOTE = (
    "<Esc>:silent! colorscheme pywal16<CR>:silent! "
    'lua pcall(function() require("lualine").refresh() end)<CR>'
    ":silent! Neotree refresh<CR>"
)


def run(cmd: list[str], *, check: bool = True,
        **kwargs) -> subprocess.CompletedProcess:
    """Wrapper around subprocess.run with check=True by default."""
    return subprocess.run(cmd, check=check, **kwargs)


def find_wallpapers() -> list[Path]:
    exts = {".jpg", ".jpeg", ".png", ".webp"}
    return sorted(
        p
        for p in WALL_DIR.rglob("*")
        if p.is_file() and p.suffix.lower() in exts
    )


def choose_wallpaper(files: list[Path]) -> Path | None:
    rofi_input = "\n".join(str(p) for p in files) + "\n"
    proc = run(
        ROFI_CMD,
        input=rofi_input,
        text=True,
        capture_output=True,
        check=False,
    )

    if proc.returncode not in (0, 1):
        proc.check_returncode()

    choice = proc.stdout.strip()
    return Path(choice) if choice else None


def refresh_neovim() -> None:
    runtime = os.environ.get("XDG_RUNTIME_DIR")
    if not runtime:
        return

    for sock in Path(runtime).glob("nvim.*"):
        if not sock.exists() or not sock.is_socket():
            continue
        run(
            ["nvim", "--server", str(sock), "--remote-send", NVIM_REMOTE],
            check=False,
        )


def apply_wallpaper(choice: Path) -> None:
    run([*SWWW_CMD, str(choice), "--transition-type",
         "any", "--transition-duration", "0.6"])
    run([*WAL_CMD, str(choice), "-n"])
    run(KITTY_CMD, check=False)
    refresh_neovim()
    run([*WAL_CMD, str(choice), "-n"])
    colors = load_wal_colors()
    update_niri_colors(colors)
    update_spicetify(colors)


def load_wal_colors() -> dict[str, Any]:
    colors_path = Path.home() / ".cache" / "wal" / "colors.json"
    with colors_path.open() as f:
        return json.load(f)


def update_niri_colors(data: dict[str, Any]) -> None:
    bg = data["special"]["background"]
    c1 = data["colors"]["color1"]
    c2 = data["colors"]["color2"]
    c4 = data["colors"]["color4"]
    c8 = data["colors"]["color8"]

    out_path = Path.home() / ".config" / "niri" / "colors.runtime.kdl"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    content = f"""// generated by wallpick (pywal)
layout {{
  focus-ring {{
    width 4
    active-color "{c4}"
    inactive-color "{c8}"
  }}
  border {{
    off
    width 4
    active-color "{c1}"
    inactive-color "{c8}"
    urgent-color "{c2}"
  }}
}}
overview {{
  backdrop-color "{bg}"
}}
"""

    with tempfile.NamedTemporaryFile("w", delete=False) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)

    shutil.move(tmp_path, out_path)
    run(
        ["niri", "msg", "reload"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )


def update_spicetify(data: dict[str, Any]) -> None:
    spicetify_bin = shutil.which("spicetify")
    if spicetify_bin is None:
        print("spicetify not found on PATH; skipping", file=sys.stderr)
        return

    spotify_path = detect_spotify_path()
    if spotify_path is None:
        print("could not detect spotify install; set spotify_path manually",
              file=sys.stderr)
        return

    theme_dir = Path.home() / ".config" / "spicetify" / "Themes" / "wal"
    theme_dir.mkdir(parents=True, exist_ok=True)
    color_file = theme_dir / "color.ini"

    colors = data["colors"]
    special = data["special"]
    content = f"""[wal]
text={colors["color7"]}
subtext={colors["color4"]}
main={special["background"]}
sidebar={colors["color8"]}
player={colors["color2"]}
card={colors["color1"]}
shadow={colors["color0"]}
selected-row={colors["color3"]}
button={colors["color5"]}
button-active={colors["color6"]}
button-disabled={colors["color8"]}
"""
    color_file.write_text(content)

    config_path = ensure_spicetify_config(spotify_path)
    env = {**os.environ, "SPICETIFY_CONFIG": str(config_path)}
    run([spicetify_bin, "apply"], check=False, env=env)
    run([spicetify_bin, "backup", "apply"], check=False, env=env)


def detect_spotify_path() -> Path | None:
    spotify_bin = shutil.which("spotify")
    if spotify_bin is None:
        return None

    resolved = Path(spotify_bin).resolve()
    spotify_dir = resolved.parent

    apps_dir = spotify_dir / "Apps"
    if apps_dir.exists():
        return spotify_dir

    share_dir = spotify_dir.parent / "share" / "spotify"
    if (share_dir / "Apps").exists():
        return share_dir

    return None


def ensure_spicetify_config(spotify_path: Path) -> Path:
    config_dir = Path(os.environ.get("XDG_CONFIG_HOME",
                                     Path.home() / ".config")) / "spicetify"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config-xpui.ini"

    cfg = configparser.ConfigParser()
    if config_path.exists():
        cfg.read(config_path)

    if "Setting" not in cfg:
        cfg["Setting"] = {}
    settings = cfg["Setting"]

    settings["spotify_path"] = str(spotify_path)
    settings.setdefault("prefs_path",
                        str(Path.home() / ".config" / "spotify" / "prefs"))
    settings["current_theme"] = "wal"
    settings["color_scheme"] = "wal"

    with config_path.open("w") as f:
        cfg.write(f)

    return config_path


def main() -> int:
    files = find_wallpapers()
    if not files:
        return 1

    choice = choose_wallpaper(files)
    if choice is None:
        return 0

    apply_wallpaper(choice)
    return 0


if __name__ == "__main__":
    sys.exit(main())
