import json
import os
import subprocess
import tempfile
from pathlib import Path

def env(name: str, default: str | None = None) -> str:
    v = os.environ.get(name, default)
    if v is None or v == "":
        raise SystemExit(f"Missing required env var: {name}")
    return v

def run(cmd, check=True, capture_output=False, text=True, input=None):
    return subprocess.run(
        cmd,
        check=check,
        capture_output=capture_output,
        text=text,
        input=input,
    )

def list_wallpapers(find_bin: str, wall_dir: Path):
    p = run(
        [
            find_bin, str(wall_dir),
            "-type", "f",
            "(",
            "-iname", "*.jpg", "-o",
            "-iname", "*.png", "-o",
            "-iname", "*.webp",
            ")",
        ],
        capture_output=True,
    )
    files = [line.strip() for line in p.stdout.splitlines() if line.strip()]
    files.sort()
    return files

def rofi_pick(rofi_bin: str, files: list[str]) -> str | None:
    p = run(
        [rofi_bin, "-dmenu", "-i", "-p", "Wallpaper"],
        check=False,
        capture_output=True,
        input="".join(f + "\n" for f in files),
    )
    choice = (p.stdout or "").strip()
    return choice if choice else None

def write_niri_theme(niri_bin: str, colors_json: Path):
    if not colors_json.exists():
        return

    data = json.loads(colors_json.read_text())
    bg = data["special"]["background"]
    c1 = data["colors"]["color1"]
    c2 = data["colors"]["color2"]
    c4 = data["colors"]["color4"]
    c8 = data["colors"]["color8"]

    out_dir = Path.home() / ".config/niri"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "colors.runtime.kdl"

    content = f"""// generated by wallpick (pywal)
layout {{
  focus-ring {{
    width 4
    active-color "{c4}"
    inactive-color "{c8}"
  }}
  border {{
    off
    width 4
    active-color "{c1}"
    inactive-color "{c8}"
    urgent-color "{c2}"
  }}
}}
overview {{
  backdrop-color "{bg}"
}}
"""

    with tempfile.NamedTemporaryFile("w", delete=False, dir=str(out_dir)) as tf:
        tf.write(content)
        tmp_name = tf.name
    os.replace(tmp_name, str(out_path))

    run([niri_bin, "msg", "action", "do-screen-transition"], check=False, capture_output=True)

def main() -> int:
    wall_dir = Path(env("WALLPICK_WALL_DIR"))
    wal_theme = env("WALLPICK_SP_THEME")

    find_bin = env("WALLPICK_FIND")
    rofi_bin = env("WALLPICK_ROFI")
    swww_bin = env("WALLPICK_SWWW")
    wal_bin = env("WALLPICK_WAL")
    kitty_bin = env("WALLPICK_KITTY")
    pywal_spicetify_bin = env("WALLPICK_PYWAL_SPICETIFY")
    spicetify_bin = env("WALLPICK_SPICETIFY")
    niri_bin = env("WALLPICK_NIRI")

    files = list_wallpapers(find_bin, wall_dir)
    if not files:
        return 1

    choice = rofi_pick(rofi_bin, files)
    if not choice:
        return 0

    # wallpaper
    run([swww_bin, "img", choice, "--transition-type", "any", "--transition-duration", "0.6"])

    # pywal16
    run([wal_bin, "-i", choice, "-n"])

    # kitty colors (best effort)
    run([kitty_bin, "@", "set-colors", "--all", "--configured", str(Path.home() / ".cache/wal/colors-kitty.conf")],
        check=False)

    # spicetify: align with earlier plan (pywal-spicetify on an existing theme folder + apply)
    run([pywal_spicetify_bin, wal_theme], check=False)
    run([spicetify_bin, "apply"], check=False)
    run([spicetify_bin, "backup", "apply"], check=False)

    # niri theme from wal json
    write_niri_theme(niri_bin, Path.home() / ".cache/wal/colors.json")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
